**SOLVING MATRIX OF TYPE AX=B USING PYTHON A is 5/5 matrix of (pi,i)
: b is 5/1 matrix of di**

**IMPLICIT CASE AFTER 10 DAYS CALCULATION OF MATRIX**

In [12]:
import numpy
A = [[-0.96821,0.126788,0,0,0],[0.126788,-1.095,0.126788,0,0],[0,0.126788,-1.095,0.126788,0],[0,0,0.126788,-1.095,0.126788],[0,0,0,0.126788,-0.96821]]
b = [-5048.54,-5098.54,-5048.54,-4898.54,-5048.54]
x = numpy.linalg.lstsq(A,b,rcond=None) 
x
## P1=6005.90945659, P2=6045.06416195, P3=5988.95801773, P4=5859.60370424,P5=5981.62323716

(array([6005.90945659, 6045.06416195, 5988.95801773, 5859.60370424,
        5981.62323716]),
 array([], dtype=float64),
 5,
 array([1.30014714, 1.17335874, 1.01663966, 0.88985126, 0.8414232 ]))

**IMPLICIT CASE AFTER 20 DAYS CALCULATION OF MATRIX**

In [13]:
import numpy
A = [[-0.96821,0.126788,0,0,0],[0.126788,-1.095,0.126788,0,0],[0,0.126788,-1.095,0.126788,0],[0,0,0.126788,-1.095,0.126788],[0,0,0,0.126788,-0.96821]]
b = [-5053.51,-5136.46,-5039.25,-4780.41,-5033.08]
x = numpy.linalg.lstsq(A,b,rcond=None) 
x
## P1=6015.4534235 , P2=6078.74687797, P3=5971.23168372, P4=5746.10006082, P5=5950.79221916

(array([6015.4534235 , 6078.74687797, 5971.23168372, 5746.10006082,
        5950.79221916]),
 array([], dtype=float64),
 5,
 array([1.30014714, 1.17335874, 1.01663966, 0.88985126, 0.8414232 ]))

**IMPLICIT CASE AFTER 30 DAYS CALCULATION OF MATRIX**


In [14]:
import numpy
A = [[-0.96821,0.126788,0,0,0],[0.126788,-1.095,0.126788,0,0],[0,0.126788,-1.095,0.126788,0],[0,0,0.126788,-1.095,0.126788],[0,0,0,0.126788,-0.96821]]
b = [-5061.54,-5164.8,-5024.34,-4684.9,-5007.14]
x = numpy.linalg.lstsq(A,b,rcond=None) 
x
## P1=6026.98248841, P2=6103.45391597, P3=5949.56133272, P4=5651.83569602, P5=5911.65650451

(array([6026.98248841, 6103.45391597, 5949.56133272, 5651.83569602,
        5911.65650451]),
 array([], dtype=float64),
 5,
 array([1.30014714, 1.17335874, 1.01663966, 0.88985126, 0.8414232 ]))

**IMPLICIT CASE AFTER 40 DAYS CALCULATION OF MATRIX**

In [15]:
import numpy
A = [[-0.96821,0.126788,0,0,0],[0.126788,-1.095,0.126788,0,0],[0,0.126788,-1.095,0.126788,0],[0,0,0.126788,-1.095,0.126788],[0,0,0,0.126788,-0.96821]]
b = [-5071.25,-5185.59,-5006.1,-4605.59,-4974.21]
x = numpy.linalg.lstsq(A,b,rcond=None) 
x
## P1=6039.32201036, P2=6121.09950192, P3=5925.64277023, P4=5571.4805009 , P5=5867.12270039

(array([6039.32201036, 6121.09950192, 5925.64277023, 5571.4805009 ,
        5867.12270039]),
 array([], dtype=float64),
 5,
 array([1.30014714, 1.17335874, 1.01663966, 0.88985126, 0.8414232 ]))

**IMPLICIT CASE AFTER 50 DAYS CALCULATION OF MATRIX**

In [16]:
import numpy
A = [[-0.96821,0.126788,0,0,0],[0.126788,-1.095,0.126788,0,0],[0,0.126788,-1.095,0.126788,0],[0,0,0.126788,-1.095,0.126788],[0,0,0,0.126788,-0.96821]]
b = [-5081.63,-5200.44,-4985.98,-4537.98,-4936.74]
x = numpy.linalg.lstsq(A,b,rcond=None) 
x
## P1=6051.62463813, P2=6133.17893554, P3=5900.5390873 , P4=5501.28410982, P5=5819.23013573

(array([6051.62463813, 6133.17893554, 5900.5390873 , 5501.28410982,
        5819.23013573]),
 array([], dtype=float64),
 5,
 array([1.30014714, 1.17335874, 1.01663966, 0.88985126, 0.8414232 ]))

**IMPLICIT CASE AFTER 60 DAYS CALCULATION OF MATRIX**

In [17]:
import numpy
A = [[-0.96821,0.126788,0,0,0],[0.126788,-1.095,0.126788,0,0],[0,0.126788,-1.095,0.126788,0],[0,0,0.126788,-1.095,0.126788],[0,0,0,0.126788,-0.96821]]
b = [-5091.98,-5210.6,-4964.85,-4478.91,-4896.44]
x = numpy.linalg.lstsq(A,b,rcond=None) 
x
## P1=6063.31759969, P2=6140.83930018, P3=5874.8708227 , P4=5438.59685195, P5=5769.39797943

(array([6063.31759969, 6140.83930018, 5874.8708227 , 5438.59685195,
        5769.39797943]),
 array([], dtype=float64),
 5,
 array([1.30014714, 1.17335874, 1.01663966, 0.88985126, 0.8414232 ]))